# 博客配置 | Blog Configuration
# keywords:
author: Qihua Gong
# description: 

# 如需修改icon,请替换 source/images/favicon.ico 文件
# If you want to change the icon, please replace the source/images/favicon.ico file
avatar: /images/favicon.ico
copyright: 2023 

# 个人信息 | Personal Information
name: Qihua Gong

# 社交账号 | Social Account
github: https://github.com/GongQihua
mail: mailto:gongqihua0115@gmail.com
linkedin: https://www.linkedin.com/in/gongqihua0115/
website: https://gongqihua.github.io/
# QQ: http://sighttp.qq.com/authd?IDKEY=xxx

# TODO：适配更多的社交账号
# TODO: Add more social accounts
